### ISSUE TITLE
CSRF Failed: Origin checking failed - https://authentik.ryuluna.com does not match any trusted origins.

### ISSUE THREAD

**Issue by yunylz** [brokenscripts/authentik_traefik#1]
hello, on API requests, especially when I want to create an app, I get `CSRF Failed: Origin checking failed - https://authentik.ryuluna.com does not match any trusted origins.` and 403 on the POST route.

**Comment by brokenscripts** [comment]
I haven't updated to the most current version due to work (hence the extremely slow response) so I would have to check.  When I have time I'll take a gander, but for an API issue you would be best off going to the actual Authentik GitHub and posting an issue

**Comment by brokenscripts** [comment]
I've updated the guide, took long enough to come back to this.  I do not see that issue, but if you run into it again, please re-open an issue.
