### ISSUE TITLE
ADD ZERO TRUST FROM CLOUDFLARE

### ISSUE THREAD

**Issue by ddiawara** [brokenscripts/authentik_traefik#10]
hello hello 
thank you for this high quality tuto, i am currently researching a few things that are very similar to what you have implemented at 90%. 
my particularity is that i use cloudflare zero trust. 
Do you think this solution holds the road or is it overkill? 

![SCR-20241112-3c-2](https://github.com/user-attachments/assets/d51aae02-fb3e-4b43-8364-94eb8782654a)

**Comment by brokenscripts** [comment]
I don't think you can ever go overkill.  Part of tinkering is just to have fun.  I'd validate no issues with pulling the tokens and that it doesn't take a ridiculous amount of time to return success.
