### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by RobotsAreCrazy** [brokenscripts/authentik_traefik#2]
Hi, Just getting into the whole traefik rabbit hole and wanting to add authentik, but one thing is how do I do the secrets file and generate passwords etc and how should it all look?

Thankyou for any help I really appreciate it 👍

**Comment by reddsimpson** [comment]
@RobotsAreCrazy this guild explains secrets and how to easy gen passwords pretty well:  https://earthly.dev/blog/docker-secrets/

**Comment by brokenscripts** [comment]
I've updated the guide to include a section on secrets at a very high level.  Please review the link @reddsimpson posted for more info.  Going to close this, if the secrets don't make sense let me know and I'll update the README.
