### ISSUE TITLE
Missing application

### ISSUE THREAD

**Issue by Forsskieken** [brokenscripts/authentik_traefik#3]
Hi There,
Thanks for this elaborate manual, it surely gives a good insight.
Still in the first part it seems I'm missing the whoami-tesst app in the explanation for the domain .
For indivisiual apps it's explained how to create, but not for the domain authentication.
Furthermore can you elaborate this with a portainer oath example.
Thanks for reading and creating this...

**Comment by brokenscripts** [comment]
I've updated the guide now to include 2 `whoami` containers on the stack startup.  Specific integrations, such as with Portainer can be found on the official website: https://docs.goauthentik.io/integrations/services/portainer/
