### ISSUE TITLE
Can't access Traefik's dashboard

### ISSUE THREAD

**Issue by habr05** [brokenscripts/authentik_traefik#6]
I'm using Authentik v2024.2.1 and everything seems to be working with an exception of Traefik's dashboard -> Traefik's dashboard Host configured with a domain + PathPrefix. When I try to access https://<sub.domain.tld>/dashboard I get Authentik branded page with "Not Found" on it. And if I comment out `"traefik.http.routers.authentik-rtr.rule=Host(`authentik.$DOMAIN`)"`, Traefik's dashboard works.

What am I missing?

![Screenshot 2024-02-28 091930](https://github.com/brokenscripts/authentik_traefik/assets/26849879/4927e2d1-f761-4650-804f-c50bda6022cb)

**Comment by brokenscripts** [comment]
I've updated the guide, but instead of residing on a path, I chose subdomains.  @habr05 did you get this fixed or are you still running into it on the latest version?
