### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by madejackson** [brokenscripts/authentik_traefik#9]
Hi,

I followed your guide today. It seems there is an issue where it doesn't work, when the folders for the volumes do not exist yet (Lot's of permission denied errors).

I think the best explanation for my issue is found here: https://stackoverflow.com/a/65092449

I waas able to solve it by issuing _chown -R uid:gid_ the docker dir after _compose up -d_.

**Comment by brokenscripts** [comment]
Thanks.  I didn't add that originally since it was just an overall guide, but for the minimal setup I took that into consideration!
